site_name: project-euler
nav:
  - Home: index.md
theme:
  name: material
  favicon: https://projecteuler.net/images/clipart/euler_portrait.png
  logo: https://projecteuler.net/images/clipart/euler_portrait.png
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - header.autohide
repo_name: coding-armadillo/project-euler
repo_url: https://github.com/coding-armadillo/project-euler
plugins:
  - search
  - tags
  - glightbox:
      auto_caption: True
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/coding-armadillo
